import {
  ERROR_FILE_NOT_FOUND,
  ERROR_FILE_SIZE_LIMIT,
  ERROR_MISSING_FILE,
  ERROR_MISSING_FILES,
  ERROR_UNSUPPORTED_FILE_TYPE,
  ERROR_UPLOAD_FAILED,
  ERROR_FOLDER_CREATION_FAILED,
} from "./errorMessages/index.js";
import {
  SUCCESS_FILES_UPLOAD,
  SUCCESS_FILE_UPLOAD,
  SUCCESS_FILE_DELETED,
  SUCCESS_FILES_DELETED,
} from "./successMessages/index.js";

export {
  ERROR_FILE_NOT_FOUND,
  ERROR_FILE_SIZE_LIMIT,
  ERROR_MISSING_FILE,
  ERROR_MISSING_FILES,
  ERROR_UNSUPPORTED_FILE_TYPE,
  ERROR_UPLOAD_FAILED,
  ERROR_FOLDER_CREATION_FAILED,
  SUCCESS_FILES_UPLOAD,
  SUCCESS_FILE_UPLOAD,
  SUCCESS_FILE_DELETED,
  SUCCESS_FILES_DELETED,
};
