import {
  ERROR_FILE_NOT_FOUND,
  ERROR_FILE_SIZE_LIMIT,
  ERROR_MISSING_FILE,
  ERROR_MISSING_FILES,
  ERROR_UNSUPPORTED_FILE_TYPE,
  ERROR_UPLOAD_FAILED,
  ERROR_FOLDER_CREATION_FAILED,
} from "./errorMessages/index.js";

export const errorMessages = {
  ERROR_FILE_NOT_FOUND,
  ERROR_FILE_SIZE_LIMIT,
  ERROR_MISSING_FILE,
  ERROR_MISSING_FILES,
  ERROR_UNSUPPORTED_FILE_TYPE,
  ERROR_UPLOAD_FAILED,
  ERROR_FOLDER_CREATION_FAILED,
};
