export const userRegisterObject = [
  {
    id: "register-name",
    name: "name",
    inputType: "text",
    placeholder: "Enter your Name",
    label: "Name",
    isRequired: false,
  },
  {
    id: "register-email",
    name: "email",
    inputType: "text",
    placeholder: "Enter your E-mail",
    label: "E-mail",
    isRequired: false,
  },
  {
    id: "register-password",
    name: "password",
    inputType: "password",
    placeholder: "Enter your Password",
    label: "Password",
    isRequired: false,
  },
  {
    id: "register-confirm-password",
    name: "confirmPassword",
    inputType: "password",
    placeholder: "Enter your confirm password",
    label: "Confirm Password",
    isRequired: false,
  },
  {
    id: "register-date-of-birth",
    name: "dateOfBirth",
    inputType: "date",
    placeholder: "Select your date of birth",
    label: "Date of Birth",
    isRequired: false,
  },
  {
    id: "register-phone-no",
    name: "phoneNumber",
    inputType: "text",
    placeholder: "Enter your Phone Number",
    label: "Phone Number",
    isRequired: false,
  },
];
